project:
  type: website

website:
  title: "Intensive Training 2024"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - sesion_1.qmd
      - sesion_2.qmd
      - sesion_3.qmd
      - sesion_4.qmd
      - sesion_5.qmd
      - sesion_6.qmd
      - sesion_7.qmd
      - sesion_8.qmd

format:
  html:
    lang: es
    theme: cosmo
    css: styles.css
    toc: true



